### ISSUE TITLE
[Fabric; 1.19.2] Crash on startup with version 1.0.0.1

### ISSUE THREAD

**Issue by SplendidAlakey** [Crystal-Nest/soul-fire-d#1]
**Describe the bug**

Crash on initialization.

Logs: https://gist.github.com/Footage2-Amply-Pounce/9395665568a0610ffc20b2b6113aef31

**To Reproduce**

1. Simply install Soul fire'd 1.0.0.1 and launch the game
2. Crash on startup

**Expected behavior**

No crash.

**Screenshots**

-

**System information:**

 - Minecraft version: 1.19.2
 - Mod version: 1.0.0.1

**Additional context**

Version 1.0.0.0 doesn't crash.

**Comment by Crystal-Spider** [comment]
Thanks for the report, I know what's causing this but I will be able to work on it only in a few hours.

**Comment by Crystal-Spider** [comment]
Should be fixed in the latest release.
