### ISSUE TITLE
Crash when used alongside Spiders 2.0

### ISSUE THREAD

**Issue by tallubhai** [Crystal-Nest/soul-fire-d#11]
**Describe the bug**

Game crashes on startup, when installed alongside [Spiders 2.0](https://www.curseforge.com/minecraft/mc-mods/spiders-2-0)

**To Reproduce**
1. Install both this mod and spiders 2.0
2. launch the game.
3. Game crashes.

**Expected behavior**

Game should not crash.

**Screenshots**

**System information:**
 - Minecraft version: 1.16.5
 - Forge 36.2.39
 - Mod version: 2.0.0.0 & 1.1.0.0 (tested both)

**Additional context**

latest.log here: https://pastebin.com/mJpaqG9m

No crash logs were generated.

**Comment by Crystal-Spider** [comment]
The crash seems to happen also with [Nyf's Spiders](https://www.curseforge.com/minecraft/mc-mods/nyfs-spiders) (port for new Minecraft versions of Spiders 2.0).

I'm looking into it.

**Comment by Crystal-Spider** [comment]
Fix completed, the new version 2.0.0.1 will soon be available for all active Minecraft versions (1.16.5, 1.18.2, 1.19.2, 1.19.3).
