### ISSUE TITLE
Quilt incompat

### ISSUE THREAD

**Issue by Sunconure11** [Crystal-Nest/soul-fire-d#15]
Mod appears to crash with Quilt 1.19.2 when using Fabric 1.19.2 builds of the mod. I am using 1.19.2 due to the decisions of some mod authors that I cannot control.

https://gist.github.com/Sunconure11/e82776e6ff8b7a1a136bbfcc4e7074e1

**Comment by Crystal-Spider** [comment]
I do not actively support Quilt, so this is not a bug and something very low priority for me.  
However, I will reach out to the Quilt support team and try to understand what may be causing the issue.

**Comment by Sunconure11** [comment]
It appears to be a versioning issue. It’s looking for a version of the API that Quilt does not use.

**Comment by Crystal-Spider** [comment]
I got an answer from the Quilt team. They do include fabricloader, but not version 0.14.12  
I can downgrade my version requirement, and I will as soon as I can.

**Comment by Crystal-Spider** [comment]
Fixed with version v3.0.0.1
