### ISSUE TITLE
Additional Enchantments and Curses - Feature Recommendation

### ISSUE THREAD

**Issue by NathanCPlaster** [Crystal-Nest/soul-fire-d#17]
I have a couple of enchantments / curses I believe would be a great feature for this mod.

Weapon Curse:  Soul Ignition - Upon dealing damage to a mob your soul ignites dealing damage to you, however any 
                          additional attacks on mobs (while on fire) do increased damage.  [Ignites with soul_fire and deals 
                           soul_fire damage]

Armor Enchantment:  Spontaneous Blaze -  Upon receiving damage the blocks around you are set on fire.

Armor Curse (boots):  Wildfire - Everywhere you step ignites the block beneath you.

**Comment by Crystal-Spider** [comment]
These are not bad suggestions, they are indeed interesting curses. However I believe they go too much out of the scope of this mod, but I may do in the future an additional mod for them.
