### ISSUE TITLE
Config to disable enchants

### ISSUE THREAD

**Issue by supersaiyansubtlety** [Crystal-Nest/soul-fire-d#2]
**Is your feature request related to a problem? Please describe.**
I'd like to use this mod but I don't want the enchantments.

**Describe the solution you'd like**
It'd be great if there were a config to disable the adding of enchantments.

**Additional context**
I'd like to add the mod to a mod set that only adds mechanics, but no 'content' to vanilla.

**Comment by Crystal-Spider** [comment]
I'm sorry, but this won't happen.  
However there are a couple of things you can do to solve your problem:
1. If you're on Fabric, you can use On Soul Fire that is basically this mod without enchantments and the API.  
Although its soul fire behavior is a little bit less consistent than mine, it still works great.
2. If you're on Forge, you can look into JEITweaker and more of its kind to remove the enchantments from the JEI, the loot tables of chests and villager trades.

**Comment by Crystal-Spider** [comment]
I decided to reopen the issue and soon to update the mod with a couple of configuration options to enable/disable the soul fire enchantments.

**Comment by Crystal-Spider** [comment]
The configuration options will be available starting from v3.0.0.0

**Comment by Crystal-Spider** [comment]
Version 3.0.0.0 is now out with the new configuration options.
