### ISSUE TITLE
soul flame not making it blue fire (only does when shot through a soul fire block)

### ISSUE THREAD

**Issue by Wary282** [Crystal-Nest/soul-fire-d#20]
idk why but soul flame doesnt make blue flame arrows for some reason but it works when i shoot through a soul fire block
doesnt work with vanilla bow and modded ones

**Comment by Crystal-Spider** [comment]
Can you please give me more information to work with? For example:
- Minecraft version;
- Mod version;
- Singleplayer/multiplayer;
- Other mods installed;
- Anything else relevant;

Also, do you happen to play with any of the CoFH mods? If so, it's a known incompatibility that I can't do anything about.

**Comment by Crystal-Spider** [comment]
Is this issue still relevant? Please update it or I will close it due to inactivity

**Comment by Crystal-Spider** [comment]
Closed for inactivity.
