### ISSUE TITLE
Mod incompatibility is creating more than 20k AoE clouds in server

### ISSUE THREAD

**Issue by Skyblocking** [Crystal-Nest/soul-fire-d#22]
**Describe the bug**
I am using a mod called Ultris as well as your mod Soul Fire'd, the Ultris mod generates new dungeons and bosses, one of which places a boss on top of a Soul Sand block which has Soul Fire on top of it. This boss is "immune" until you snuff out the Soul Fire and then the boss fight actually begins.

The thing is, I think that your mod has an issue whenever there is a mob standing on top of Soul Fire indefinitely without receiving damage, which causes a lot of Area of Effect Cloud entities to start spawning in a never ending loop.

In this scenario, until the boss is disturbed, the Soul Fire'd mod is creating an infinite amount of Area of Effect Clouds that causes my server to overload and eventually crash because of the Server Watchdog that gets called in response of a tick loop. (I think the latter might be caused by this incompatibility)

**To Reproduce**
1. Install the latest version of Soul Fire'd (3.1.0.0) for Forge 45.0.64 and Minecraft 1.19.4
2. Have an immune mob standing still on top of Soul Fire and for an indefinite amount of time
3. Use F3 and look directly in the direction of the Soul Fire and check on the number of entities that are present in front of you.

**Expected behavior**
There should be a constant increasing amount of entities spawning, in this case, they should be Area of Effect Cloud entities.

**Screenshots**
1. https://github.com/Nyphet/soul-fire-d/assets/96800456/90689e44-a366-4a1c-ad31-8e9e4d24a79d
2. https://github.com/Nyphet/soul-fire-d/assets/96800456/0f2153f9-6357-4e84-b798-0e7cb94f9963

Video I recorded showcasing the bug:
1. https://youtu.be/cJiB4LOtg94

**System information:**
 - Minecraft version: 1.19.4
 - Mod version: 3.1.0.0

**Additional context**
The screenshots I am adding were taken while troubleshooting with another mod called Spark.

**Comment by Crystal-Spider** [comment]
Hi! Thank you for the report!

I will make sure to look into this as soon as I have more free time (I'm currently about to graduate and my free time is very low unfortunately).

In the mean time, could you consider opening an issue or asking to the Ultris mod creator for help? Their source code is not open-source, so it makes it more difficult for me to look into the issue (which means it requires more time, time that I currently do not have). Let me know if you get any updates on it.

If this does not get resolved on Ultris side, I will make sure to look into this properly as soon as possible.

Thanks again!

**Comment by Skyblocking** [comment]
Hello, it is nice meeting you!

I hope everything goes well with your graduation and you succeed on getting that sweet degree, I know you deserve it! I understand if you do not have enough time, there are priorities in life, honestly, do not worry about it.

As of right now, I am getting in touch with the Ultris: Boss Expansion mod author on Discord since they do not have a github page, and answering some of his questions about the issue in order to help solve the bug.

Screenshot of the interaction:
![Captura de pantalla 2023-05-24 162415](https://github.com/Nyphet/soul-fire-d/assets/96800456/90efc2e8-3512-448b-ac74-1885f1c429ab)

I'll let you know as soon as I can about whether there is progress or not on the issue with the author of the other mod.

Kind regards!

**Comment by Skyblocking** [comment]
Whoops, I clicked on the wrong button. Sorry! I think I might have moved this issue by mistake to a Done state on your project's management board.

I hope you can fix this, once again, I apologize.

**Comment by Skyblocking** [comment]
Hello again!
After communicating with the Ultris mod author, it seems that he has solved the issue on his part. He just uploaded a new version of his mod on modrinth!

Screenshot of the conversation:
![Captura de pantalla 2023-05-24 172639](https://github.com/Nyphet/soul-fire-d/assets/96800456/43ca6a47-08df-44c7-8c76-21aa7a2176c6)

It seems that it solved the issue of Area of Effect Cloud entities for their mod, but I am not sure if there is something you could fix on your side too.
![2023-05-24_18 03 57](https://github.com/Nyphet/soul-fire-d/assets/96800456/81a72269-ec16-44cb-9404-2cb16f7903c8)
![Captura de pantalla 2023-05-24 173125](https://github.com/Nyphet/soul-fire-d/assets/96800456/c13e50e3-8732-4142-8654-5170f873880a)

Either way, if there is something else I can help you with, just let me know, thank you very much!

**Comment by Crystal-Spider** [comment]
So does the issue still happen after their fix?

Thank you for your effort and speed btw!

**Comment by Skyblocking** [comment]
No problem! It is a pleasure helping in anything I can.
As for the bug, I have not done any more testing, but for now, it seems that it was solved after their fix.
I will keep an eye out for anything regarding your mod and if anything happens, I'll let you know!

**Comment by Crystal-Spider** [comment]
Okay, thank you!  
I will close the issue now, but comment anytime if you need anything else and I'll reopen it.
