### ISSUE TITLE
The mod makes items become invisible on vanilla and vanilla like servers

### ISSUE THREAD

**Issue by Dan-random** [Crystal-Nest/soul-fire-d#23]
**Description**
The bug makes items of any kind become invisible but
still be  able to be interacted with, it only occurs on **multiplayer** 
but in single player you're able to see the items normally.

**How to Reproduce**
-install the mod normally 
-join any vanilla or vanilla like server
-then drop a item into the ground
-it should be invisible and you should be able to pick it up but not see it.

**System information:**
 - Minecraft version: **1.19.2 (Fabric loader 0.14.21)**
 - Mod version: **soulfired-1.19.2-3.1.0.0-final-fabric**

**Extra info**
The servers that it happened to me where:

**5b5t.org**
**mc.hypermine.net**

**Comment by Crystal-Spider** [comment]
This mod is required both on client and server.
