### ISSUE TITLE
Soul fire blaze

### ISSUE THREAD

**Issue by Rad586** [Crystal-Nest/soul-fire-d#26]
**Is your feature request related to a problem? Please describe.**
Blaze+soul fire=soul fire blaze, soul fire blaze+fire=blaze. That would be cool. 

**Describe the solution you'd like**
1. Blaze takes soul fire damage, but it would turn into soul fire blaze after few seconds(with _item.firecharge.use_ effect). Soul fire blazes are immune to soul fire damage, but takes vanilla fire damage. So when it takes vanilla fire damage, it would turn back to normal blaze shortly after. 
2. Soul blazes replace blazes in soul sand valley. 
3. Doesn't affect blaze that has nametag or custom nbt tags.

**Describe alternatives you've considered**
Soul fire blaze spawns naturally(turned off by default) with configurable weight.  Could be seen as an elite blaze. 

**Additional context**
Fun and resonable, but may be a bit too much?

**Comment by Crystal-Spider** [comment]
Hi!  
Thank you for the support!

Yes, I do believe it's a bit too much and it goes out of the scope of this mod, especially considering that if I add Soul Fire Blazes I should also add custom blazes for all other registered fire with that option.  
However it does sound fun and reasonable, so maybe other modders or myself in the future can consider making an addon for it.

Thanks again!
