### ISSUE TITLE
Soul campfire doestn't work right

### ISSUE THREAD

**Issue by GoldenTotem** [Crystal-Nest/soul-fire-d#28]
**Describe the bug**
Mobs on soul campfire will take damage slower than vanilla. 

**To Reproduce**
1. Install mod.
2. Summon a husk on soul campfire, it will take damage 1 time per second (1Hz).
3. Uninstall mod.
4. Husk on campfire or soul campfire will take damage 2 times per second (2Hz).

**Expected behavior**
The damage frequency of mobs on soul campfire is as same as vanilla (2Hz).

**System information:**
 - Minecraft version: 1.16.5
 - Forge version: 36.2.35
 - Mod version: 3.2.0.0

**Comment by Crystal-Spider** [comment]
Just to let you know, I did replicate the issue and I found out what the problem is. I think I have a way to fix it, but I'm busy lately so I don't know when I'll have time to work on it. However the fix is definitely coming before the end of October (most likely before half of October).
