### ISSUE TITLE
2nd Skin layer doesnt show when playing on a server

### ISSUE THREAD

**Issue by figmellow** [Crystal-Nest/soul-fire-d#29]
**Describe the bug**
removes 2nd skin layer when playing on any minecraft server

**To Reproduce**
1. play on a server with soulfired installed

**Expected behavior**
not do this shit

**Screenshots**
before - https://femboy.beauty/_EGD3
after - https://femboy.beauty/gBVyL

**System information:**
 - Minecraft version: 1.20.1 Quilt
 - Mod version: v3.2.0.0

**Additional context**
doesn't do this in private world
:3 thanks 

https://femboy.beauty/_y6NR only mods i have installed

**Comment by Crystal-Spider** [comment]
Is the mod installed on **both** client **and** server?

**Comment by figmellow** [comment]
no, its just a vanilla server

**Comment by Crystal-Spider** [comment]
Then it's not a bug.  
It is stated explicitly that this mod must be installed on both sides to work properly.

**Comment by figmellow** [comment]
oh ok sorry! <3
