### ISSUE TITLE
Issue with soul flame (bow)

### ISSUE THREAD

**Issue by clashyboi805** [Crystal-Nest/soul-fire-d#31]
**Describe the bug**
When using a tetra bow with soul flame, the bow fires normal fire and ignites normal fire
**To Reproduce**
soul flame on a tetra mod bow
**Expected behavior**
it should fire soul flames
**System information:**
 - Minecraft version: 1.19.2
 - Mod version: 3.2.0.1 forge

**Additional context**
this only happens with tetra bows and not vanilla bows.

**Comment by clashyboi805** [comment]
it seems like tetra bows are the problem, not vanilla ones

**Comment by Crystal-Spider** [comment]
So, from what I can see, it's an issue with Tetra.  
Basically its bow item does not extend Vanilla bow item and it just has its own method for firing arrows.  
The solution is for Tetra to add Soul Fire'd as an optional dependency and use its API to add the proper fire behavior.

Feel free to open an issue with Tetra and copy-paste my brief explanation, even tagging me if something new arises!

**Comment by clashyboi805** [comment]
thank you! I will open an issue right now.

**Comment by Crystal-Spider** [comment]
Tetra will become compatible with Soul Fire'd when the newest version of Tetracelium will become available!
