### ISSUE TITLE
Cons for enchantments

### ISSUE THREAD

**Issue by Disketaa** [Crystal-Nest/soul-fire-d#33]
I'm thinking that every minecraft enchantment seems pretty balanced, so why soul flame enchant will damage more but also doesn't have a negative stat.

Here my ideas:
- Released arrows can't be pick-able
- Released arrows can set you on soul fire after you pick them / regular flammable arrows could do this too
- Soul fire burning can be half duration compare to regular flame (you be able to choose between fast high damage or slow but longer damage) 
(_I prefer this one_) ↑
 - Soul fire arrows fly only half a distance

**Comment by Disketaa** [comment]
Here one more:

- Item will lose its durability twice as faster

**Comment by Crystal-Spider** [comment]
Take Mending for example: it is quite OP, but its rarity makes up for it.  
Soul Fire enchantments are rarer than normal fire enchantments to make up for their greater power.

Anyway, I'll think about adding a config option to halve the duration of Soul Fire from enchantments and update you here.

**Comment by Disketaa** [comment]
Mending is quite OP I agree, but anyway it have Infinity as exclusive enchant so you need to choose between mending and infinity. But choosing between flame and soul flame doesn't work because you want soul one cause of higher damage

**Comment by Crystal-Spider** [comment]
Then what about swords or axes or armors or anything else with mending?  
The only thing balancing mending a bit is it's difficulty to obtain. Soul Fire enchantments are meant to be harder to get, furthermore they can't be put together with other fire enchantments. This last thing has the following 2 implications:

1. Either you don't put Fire Aspect/Flame until you find their Soul versions, which means not having your weapons deal fire damage for a good while, or you need to disenchant your weapons and apply the enchantments all over again.
2. Maybe in the future more mods with custom fires using this mod API will appear and their enchantments will, by default, too be exclusive with other fire enchantments, giving the player a choice for what to apply.

Finally, there are configuration options to tweak how difficult it is to obtain Soul Fire enchantments, for example by setting them to treasure only and preventing them from being obtainable in the enchanting table. Check out the configuration.

Btw, as a side note, my take is that mending and infinity shouldn't be exclusive in the first place ahah

**Comment by Disketaa** [comment]
Understood your point :)
I will balance this enchant by making it rarer tho

**Comment by Crystal-Spider** [comment]
Yes, feel free to do it! That's exactly what the configuration options are there for!
