### ISSUE TITLE
Looking for assistance with Game Crash

### ISSUE THREAD

**Issue by realrogue** [Crystal-Nest/soul-fire-d#41]
**Describe the bug**
Game crashes every time with Soul Fire'd loaded. It used to work just fine, but somewhere along the line it has simply stopped launching as long as Soul Fire'd is enabled. I'm sure it's a mixin conflict somewhere, but I don't have the knowledge to be able to read the logs to tell me exactly which mod or mods it's conflicting with.
Yes I know I'm heavily modified, but everything was working. I had some issues with quilt loader which i fixed by updating, but even rolling back all changes, the game still crashes.
Any assistance would be greatly appreciated!

**System information:**
 - Minecraft version: 1.19.2
 - Mod version: 3.2.10

**MC Logs**
[Log Link](https://mclo.gs/5KkwCGO)

**Comment by Crystal-Spider** [comment]
Are you sure that if you leave your modpack instance as is and just remove Soul Fire'd, the game won't crash?  
If so, try also to leave Soul Fire'd in, remove Mixin Conflict Helper, and let me know the result.  
Last thing, you can try to make a new instance of your modpack, reinstall the same mods, and check whether the issue persists.

Let me know!

**Comment by realrogue** [comment]
Thanks for taking the time to respond - I really appreciate you and your work.

Yes if I simply disable Soul Fire'd through Prism Launcher, the game launches fine. As soon as I enable it, it crashes.

I tried to launch with Soul Fire'd enabled, and Mixin Conflict Helper disabled, and got the same crash.

I have also already tried duplicating the instance several times with different methods, always crashes as long as Soul Fire'd is enabled.
I have even tried deleting all config files from the .minecraft directory, no dice.

**Comment by Crystal-Spider** [comment]
Could you please provide the log when Mixin Conflict Helper is disabled?

Do you have any way of sharing the modpack? For example, is it published? I'd like to try and replicate the issue myself, and I need to know whether there is a faster way than manually searching for 295 mods to add ahah  
If not, don't worry, but it'll take me a while to setup the same modpack locally.

Thanks for your kind words and your patience!

**Comment by realrogue** [comment]
Hey champion, here is log file with Mixin Conflict Helper disabled and Soul Fire'd enabled: https://mclo.gs/hD5QYFJ

It's not a modpack i've downloaded, it's all fully custom built by me over hours and hours of tweaking haha.
I've uploaded the zip file here, it can be imported by Prism Launcher and added as a instance.

[link redacted]

**Comment by Crystal-Spider** [comment]
Can you make one last attempt at it by removing Danger Close but keeping both Mixin Conflict Helper and Soul Fire'd in? Thanks.

**Comment by realrogue** [comment]
oh my god that was it! you found it!!
absolute legend.
Even with Mixin Conflict Helper enabled, as long as Danger Close is disabled, everything works.
thank you so much.
I've sent you a gift on Ko-Fi, your efforts do not go unnoticed. Have a great week!

**Comment by Crystal-Spider** [comment]
Okay, good to know we found the issue!  

More specifically, this is a compatibility issue with Danger Close, as the compatibility on its side has not yet been implemented for 1.19.2 (it's currently only for 1.20.x versions).  
This is the relevant part of the log that, most likely, Mixin Conflict Helper was, for some reason, hiding from the log before:

> [17:59:34] [main/ERROR]: Mixin apply for mod soulfired failed #soulfired:soulfired.mixins.json:CampfireBlockMixin from mod soulfired -> net.minecraft.class_3922: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException @ At("INVOKE") on net/minecraft/class_3922::redirectDamage with priority 1000 cannot inject into net/minecraft/class_3922::method_9548(Lnet/minecraft/class_2680;Lnet/minecraft/class_1937;Lnet/minecraft/class_2338;Lnet/minecraft/class_1297;)V merged by net.ggwpgaming.dangerclose.mixin.CampfireBlockMixin with priority 1000 [PREINJECT Applicator Phase -> #soulfired:soulfired.mixins.json:CampfireBlockMixin from mod soulfired -> Prepare Injections ->  -> redirect$epa000$soulfired$redirectDamage(Lnet/minecraft/class_1297;Lnet/minecraft/class_1282;F)Z -> Prepare]
> 885 | org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @ At("INVOKE") on net/minecraft/class_3922::redirectDamage with priority 1000 cannot inject into net/minecraft/class_3922::method_9548(Lnet/minecraft/class_2680;Lnet/minecraft/class_1937;Lnet/minecraft/class_2338;Lnet/minecraft/class_1297;)V merged by net.ggwpgaming.dangerclose.mixin.CampfireBlockMixin with priority 1000 [PREINJECT Applicator Phase -> #soulfired:soulfired.mixins.json:CampfireBlockMixin from mod soulfired -> Prepare Injections ->  -> redirect$epa000$soulfired$redirectDamage(Lnet/minecraft/class_1297;Lnet/minecraft/class_1282;F)Z -> Prepare]

@jason13official I'm tagging you to let you know about this, since you said "unless an issue gets reported on either of our ends" in the [other issue](https://github.com/Crystal-Nest/soul-fire-d/issues/34#issuecomment-2031024339).

@rogueda unfortunately, you have to remove either Soul Fire'd or Danger Close for the time being and wait until compatibility is added. Meanwhile, **thanks a lot** for your support!

**Comment by jason13official** [comment]
I'll have this fixed soon 🙏 Thank you for tagging me
