### ISSUE TITLE
Game Crash when Collective is installed

### ISSUE THREAD

**Issue by nco2k** [Crystal-Nest/soul-fire-d#44]
### I have confirmed no other issue reports this bug

- [X] I have searched for existing issues

### I have confirmed the mod is installed on the proper side

- [X] I have installed the mod properly

### Current behavior

game crash on launch

### Expected behavior

no game crash on launch

### Steps to reproduce

1.) install mods
2.) launch game

### Minecraft version

1.20.4

### Mod loader version

Fabric 0.15.11

### Mod version

1.20.4-3.3.0-alpha

### Other mods

Cobweb 1.20.4-0.0.3.5-beta
Collective 1.20.4-7.61-fabric+forge+neo
Fabric API 0.97.1+1.20.4
Forge Config API Port v20.4.3-1.20.4-Fabric

### Stacktrace and logs

https://mclo.gs/AGBbS2R

### Additional context

!!! only crashes when Collective is installed, but the previous Soul Fire'd version 3.2.1.0 didnt have this issue !!!

**Comment by Crystal-Spider** [comment]
I could replicate the issue, it seems to crash without Collective too.

**Comment by Crystal-Spider** [comment]
Fixed in v3.3.1-alpha
