### ISSUE TITLE
[Compatibility]: Low On Fire

### ISSUE THREAD

**Issue by Fyoncle** [Crystal-Nest/soul-fire-d#47]
### I have confirmed no other issue asks for this

- [X] I have searched for existing issues

### Other mod

https://modrinth.com/resourcepack/low-on-fire

### Current behavior

The overlay is too annoying and blinds you completely, Low On Fire meant to fix that but doesn't fix it for Soul Fire'd

### Desired behavior

Overlay down below just like Low On Fire applies to the Vanilla Fire.

### Stacktrace and logs

No need.

**Comment by Crystal-Spider** [comment]
You need to open an issue with Low On Fire, they need to provide overriding texture files.

I'll leave you some more info you can use to open the issue there:

Soul Fire'd uses Vanilla Minecraft soul fire sprites. To change the aspect of HUD fire a texture pack needs to:
* Changes the soul_fire_0 and soul_fire_1 sprites (under assets\minecraft\textures\block), in this case lowering the fire
* Changes the block models for soul fire such that it uses the "old" (Vanilla) textures. To do this one needs to duplicate the original soul fire sprites and rename them, along with changing the reference in the block json models.

Both points are already done for normal fire by that texture pack, it would need to do the same for soul fire.

**Comment by Fyoncle** [comment]
> You need to open an issue with Low On Fire, they need to provide overriding texture files.
> 
> I'll leave you some more info you can use to open the issue there:
> 
> Soul Fire'd uses Vanilla Minecraft soul fire sprites. To change the aspect of HUD fire a texture pack needs to:
> 
> * Changes the soul_fire_0 and soul_fire_1 sprites (under assets\minecraft\textures\block), in this case lowering the fire
> * Changes the block models for soul fire such that it uses the "old" (Vanilla) textures. To do this one needs to duplicate the original soul fire sprites and rename them, along with changing the reference in the block json models.
> 
> Both points are already done for normal fire by that texture pack, it would need to do the same for soul fire.

They don't have a github page ;(

**Comment by Crystal-Spider** [comment]
You could try asking on their [CurseForge page](https://www.curseforge.com/minecraft/texture-packs/low-on-fire/comments), but I see that there are already 2 comments asking for it, but it doesn't seem that any action has been taken.

If they still don't reply to you by the end of this weekend, let me know and I'll publish a texture pack myself to fix this.

**Comment by Fyoncle** [comment]
> You could try asking on their [CurseForge page](https://www.curseforge.com/minecraft/texture-packs/low-on-fire/comments), but I see that there are already 2 comments asking for it, but it doesn't seem that any action has been taken.
> 
> If they still don't reply to you by the end of this weekend, let me know and I'll publish a texture pack myself to fix this.

❤️

**Comment by Crystal-Spider** [comment]
I'm working on releasing the texture pack for low fire with Soul Fire'd.

**Comment by Crystal-Spider** [comment]
I completed the texture pack, of which you can find the source code [here](https://github.com/Crystal-Nest/slim-fire/tree/v1.0.0), and now it's just a matter of how quick CurseForge and Modrinth will be in releasing it.

In the meantime, you can:
* Come chat on our [Discord](https://discord.gg/BP6EdBfAmt), where I'll make an announcement when the texture pack will be available.
* Check for yourself every now and then the links for [CurseForge](https://www.curseforge.com/minecraft/texture-packs/slim-fire) and [Modrinth](https://modrinth.com/resourcepack/slim-fire).
* Support us on [Kofi](https://ko-fi.com/crystalspider) or [Patreon](https://www.patreon.com/crystalspider), which helps us a lot into putting more time into our many projects!

**Comment by Fyoncle** [comment]
> I completed the texture pack, of which you can find the source code [here](https://github.com/Crystal-Nest/slim-fire/tree/v1.0.0), and now it's just a matter of how quick CurseForge and Modrinth will be in releasing it.
> 
> In the meantime, you can:
> 
> * Come chat on our [Discord](https://discord.gg/BP6EdBfAmt), where I'll make an announcement when the texture pack will be available.
> * Check for yourself every now and then the links for [CurseForge](https://www.curseforge.com/minecraft/texture-packs/slim-fire) and [Modrinth](https://modrinth.com/resourcepack/slim-fire).
> * Support us on [Kofi](https://ko-fi.com/crystalspider) or [Patreon](https://www.patreon.com/crystalspider), which helps us a lot into putting more time into our many projects!

Amazing job just in a little time period, my big respects sir!
