### ISSUE TITLE
Compability with Via

### ISSUE THREAD

**Issue by dakfolz** [Crystal-Nest/soul-fire-d#48]
### I have confirmed no other issue asks for this

- [X] I have searched for existing issues

### Other mod

ViaFabric, ViaVersion

### Current behavior

I downloaded "Soul Fired" and "Cobweb", because of some mod of them it does not run on old servers using the mod "VIaFabric" and "ViaVersion"

### Desired behavior

I would like to see compatibility

### Additional context

Nothing

**Comment by Crystal-Spider** [comment]
Please, elaborate more on what "it does not run on old servers" mean

**Comment by dakfolz** [comment]
The ViaVersion mod "Allow newer clients to connect to older servers." Due to "Soul Fired" or "Cobweb", an error pops up when trying to log in to old servers.

**Comment by Crystal-Spider** [comment]
Do the servers have Soul Fire'd installed?

**Comment by dakfolz** [comment]
No, but the mod works both when installed on the server and on the client

**Comment by Crystal-Spider** [comment]
Soul Fire'd is required on both server and client, it cannot work properly if installed on one side only.

**Comment by dakfolz** [comment]
It's very disappointing. I thought it was because of incompatibility, I apologize for the time spent and thank you for the answer!
