### ISSUE TITLE
Crash on start (again)

### ISSUE THREAD

**Issue by entusiastaIA** [Crystal-Nest/soul-fire-d#5]
**Describe the bug**
I've seen this has happened before, but cannot know the reason. On latest Fabric 1.18.2 version (and previous one), 1.1.0.0 (and 1.0.0.2), if I add the mod i cannot launch minecraft.

![Captura](https://user-images.githubusercontent.com/113212323/195224545-3ccb5caf-d80b-41d2-aeaa-619b4cedc0ca.PNG)

**Comment by Crystal-Spider** [comment]
The reason of the crash is similar, but different.  
Basically another mod is trying to modify the same part of the code I do, and so it crashes.  
The incompatible mod is [sihywtcamd](https://github.com/sf-inc/sihywtcamd) (So I heard you were talking crap about Minecraft's difficulty?).  

Anyway, using the latest versions of Soul Fire'd and sihywtcamd I can't replicate the issue (my game launches) for 1.19.2.  
Using 1.18.2 I can replicate the issue, but it's likely an issue of sihywtcamd: most probably its latest 1.18.2 version does not include commit [c032277b48b02a09d38efd957e3c99c23f550d6f](https://github.com/sf-inc/sihywtcamd/commit/c032277b48b02a09d38efd957e3c99c23f550d6f) that fixed incompatibility with other mods.

I opened a new issue on the other mod GitHub.

**Comment by entusiastaIA** [comment]
Thank you very much for taking the time to check it this much! Could that issue with that mod affect other one's too? I am trying to narrow down random crashes I am getting that afterwards leave the world unloadable.

I can confirm that removing sihywcamd and enabling back SoulFire'd allow me to run the game again.

**Comment by Crystal-Spider** [comment]
Definitely this issue can affect other mods, but only if other mods are changing something in the behavior of a Zombie attack.  
On my end I cannot do anything to fix this, it's up to sihywcamd to fix that by porting the fix that's already in 1.19.2 to 1.18.2.

If it's fine for you, I'd close this issue and you can follow the progress on the [other issue](https://github.com/sf-inc/sihywtcamd/issues/35) I opened on sihywcamd.

**Comment by entusiastaIA** [comment]
Perfect thank you!

**Comment by charlyb01** [comment]
Hello, I'm going to update the 1.18 version to get the fix then. Sorry for that, I noticed it a bit late so it stayed on this version!
[Edit] Done!

**Comment by entusiastaIA** [comment]
Thank you very much, I updated and it is working! :)
