### ISSUE TITLE
生物被带有魂焰附加的剑秒杀后，掉落生肉

### ISSUE THREAD

**Issue by 19707677707** [Crystal-Nest/soul-fire-d#50]
### I have confirmed no other issue asks the same question

- [X] I have searched for existing issues

### Question

生物被带有魂焰附加的剑秒杀后，掉落生肉，这是什么特性吗，火焰附加不会这样，还是一个bug？

### Additional context

生物被带有魂焰附加的剑秒杀后，掉落生肉，这是什么特性吗，火焰附加不会这样，还是一个bug？

**Comment by Crystal-Spider** [comment]
Please, use english

**Comment by Crystal-Spider** [comment]
Fixed with [v5.0.2](https://github.com/crystal-nest/soul-fire-d/releases?q=5.0.2).
