### ISSUE TITLE
Skeleton with soul flame shoot orange flame arrows

### ISSUE THREAD

**Issue by lzm11111111** [Crystal-Nest/soul-fire-d#51]
### I have confirmed no other issue reports this bug

- [X] I have searched for existing issues

### I have confirmed the mod is installed on the proper side

- [X] I have installed the mod properly

### Current behavior

Skeleton with soul flame shoot orange flame arrows instead of blue

### Expected behavior

Skeleton with soul flame shoot blue flame arrows

### Steps to reproduce

1. Give the skeleton a soul flame bow
2. Let it attacking you

### Minecraft version

1.20.1

### Mod loader version

*

### Mod version

*

### Other mods

*

### Stacktrace and logs

*

### Additional context

I found a bug, when you give the skeleton a soul flame bow, it will shoot orange flame arrows instead of blue.

https://github.com/user-attachments/assets/3baf19b1-a0b9-4eb5-bd7c-49e965ae43dd

**Comment by Crystal-Spider** [comment]
Thanks for the report, please complete with the additional information required to assist you better:

- Mod loader version
- Mod (Soul Fire'd) version
- Other mods installed
- latest.log and debug.log

**Comment by lzm11111111** [comment]
It seems fixed in Latest version, I seem to have misreported, sorry.

**Comment by lzm11111111** [comment]
It seems to be fixed in the latest version, I misreported it, sorry.

![2024-08-05_11 34 58](https://github.com/user-attachments/assets/4935735d-6c61-4a4c-afea-d7e240e3ea57)
