### ISSUE TITLE
Unable to join any server

### ISSUE THREAD

**Issue by Tatertot5s** [Crystal-Nest/soul-fire-d#56]
### I have confirmed no other issue reports this bug

- [X] I have searched for existing issues

### I have confirmed the mod is installed on the proper side

- [X] I have installed the mod properly

### Current behavior

When a player tries to join any server, they get "Network Protocol Error", and they are unable to join.

### Expected behavior

Player Joins Server

### Minecraft version

1.21

### Mod loader version

Fabric 0.16.5

### Mod version

5.0.2

### Other mods

Fabric API 0.102.0
Cobweb 1.1.2

### Stacktrace and logs

mclo.gs:
https://mclo.gs/uIWUZ1z

pastebin:
https://pastebin.com/4J02G9Ya

**Comment by Crystal-Spider** [comment]
Does the server have the mod installed?

**Comment by Tatertot5s** [comment]
No, it doesn't. I was under the impression that this is a client side mod. Am I wrong?

EDIT: Just checked the mod page, yeah it dose say that it needs to be used on client and server. I would figure the mod would disable itself when it's not on the server.

**Comment by Crystal-Spider** [comment]
I can't make it disable itself because of how entities need to be handled unfortunately.

This mods needs to be on both server and client to work.
