### ISSUE TITLE
Crash on start with some other mod

### ISSUE THREAD

**Issue by SkyRunner55** [Crystal-Nest/soul-fire-d#57]
### I have confirmed no other issue reports this bug

- [X] I have searched for existing issues

### I have confirmed the mod is installed on the proper side

- [X] I have installed the mod properly

### Current behavior

Crash when starting the game, i guess its a problem with the other mods i have
![Capture d'écran 2024-09-22 000733](https://github.com/user-attachments/assets/becb9400-f03e-4e5b-a642-d09e4fc8437f)

### Expected behavior

The mod was working properly before i started to put some other mods

### Minecraft version

1.21.1

### Mod loader version

21.1.57 Neoforge 

### Mod version

v5.0.2

### Other mods

[modlist.txt](https://github.com/user-attachments/files/17085878/modlist.txt)
(this was a html)

### Stacktrace and logs

[crash-2024-09-21_15.46.17-fml.txt](https://github.com/user-attachments/files/17085885/crash-2024-09-21_15.46.17-fml.txt)

### Additional context

i'm tried my best to help, first time reporting a bug on github

**Comment by Crystal-Spider** [comment]
Why do you think it's an issue with this mod?  
From the crash log I see this:  

> Mod file: /C:/Users/aurel/curseforge/minecraft/Instances/Sky's Modpack (Client Side)/mods/justzoom_neoforge_2.0.0_MC_1.21-1.21.1.jar
> Failure message: Mod justzoom requires konkrete 1.9.0 or above
> Currently, konkrete is not installed

However, I also see that Konkrete is in the mod list, so something weird is happening.  
If you remove Soul Fire'd, does everything work?

Anyway, you can try sharing the launcher log too, it might have more accurate infos. To do so, you have to:

1. Open the launcher and click the "Installations" tab at the top.
2. Hover over the game profile and click the folder icon.
3. There should be a file called launcher_log.txt . If you can't find it, try opening the %AppData%\.minecraft folder and looking there.
4. Go to https://pastebin.com/ or https://paste.ee/ and paste the contents of the launcher log there, then share the link here.

**Comment by SkyRunner55** [comment]
[launcher_log.txt](https://github.com/user-attachments/files/17085948/launcher_log.txt)
This one ? , i'm using cursedforge to play minecraft with mods, and alos koncrete is installed with the good version

hope ive done this the good way

**Comment by Crystal-Spider** [comment]
That seems to be the correct file, but I can't see anything about the crash.  
But I also just noticed that you're playing on 1.21.1, but there is no Soul Fire'd version for 1.21.1, so what's going on?  
Also, please, let me know the answer to the questions in my previous comment.

Btw, don't worry, you're doing everything just fine!

**Comment by SkyRunner55** [comment]
if i remove soul fire'd yes it work, and mods in 1.21 work in 1.21.1 since its a very minor update (2 language support & 2 bug fix) https://minecraft.wiki/w/Java_Edition_1.21.1

**Comment by Crystal-Spider** [comment]
Try going into the launcher settings (bottom left), then check both "Keep open the launcher while games run" and "Open the output log at the start of Minecraft: Java Edition".  
Once you play the game, it should open a new window with the logs, and you can copy its content and send it here.

**Comment by SkyRunner55** [comment]
[Startlog.txt](https://github.com/user-attachments/files/17088932/Startlog.txt)

**Comment by Crystal-Spider** [comment]
Could you please export the modpack and send it here? So I can test whether the error comes from an incompatibility with some other mod.

**Comment by SkyRunner55** [comment]
[My Modpack.zip](https://github.com/user-attachments/files/17089283/My.Modpack.zip)

**Comment by Crystal-Spider** [comment]
So, after some testing, there seems to be an issue with Soul Fire'd (or Cobweb) and the amount of installed mods.  
Not sure what's causing this, but I'll let you know as soon as I do.

**Comment by Crystal-Spider** [comment]
It should be fixed with v5.0.3, could you please confirm it?

**Comment by SkyRunner55** [comment]
there is no more crash on start up

**Comment by SkyRunner55** [comment]
The mod works perfectly :D

**Comment by Crystal-Spider** [comment]
Great!
