### ISSUE TITLE
Compatibility List addition with Alexs Mobs Interaction

### ISSUE THREAD

**Issue by CrimsonCrips** [Crystal-Nest/soul-fire-d#58]
### I have confirmed no other issue asks the same question

- [X] I have searched for existing issues

### Question

https://www.curseforge.com/minecraft/mc-mods/alexs-mobs-interaction

### Additional context

https://github.com/CrimsonCrips/AlexsMobsInteraction/blob/d63006c434697193d37dd93709154cea0a8ec0be/src/main/java/com/crimsoncrips/alexsmobsinteraction/compat/SoulFiredCompat.java

https://github.com/CrimsonCrips/AlexsMobsInteraction/blob/1ec41f9ebe09b9e4250e52021895ef0e65dcf23d/src/main/java/com/crimsoncrips/alexsmobsinteraction/event/AMInteractionEvents.java#L869-L873

**Comment by CrimsonCrips** [comment]
additional proof if needed
![image](https://github.com/user-attachments/assets/b95966aa-9689-46dc-841a-94f7432d97f6)

**Comment by Crystal-Spider** [comment]
Do you happen to host your mod on Modrinth too?

**Comment by CrimsonCrips** [comment]
yes

**Comment by Crystal-Spider** [comment]
Could you please provide a link for that too?

**Comment by CrimsonCrips** [comment]
https://modrinth.com/mod/alexs-mobs-interaction
